#!/usr/bin/env ruby
# frozen_string_literal: true
#
# To update this script, please update in github.com/truecoach/ops via
# pull request, then copy-paste the updated version here.
#
# # DESCRIPTION # #
#
# Creates a release branch and opens the compare view in github
#
status = `git status --porcelain`
raise 'Unclean git working state. Please stash or commit your changes first.' unless status == ''

now = Time.now.strftime("%-m-%-d-%Y-%-l.%M%P")
tz = Time.now.getlocal.zone
branch_name = "release/#{now}-#{tz}"

if ENV['REPO_URL'].nil?
  repo_name = `basename $(git remote get-url origin)`.chomp(".git")
  repo_url = "https://github.com/truecoach/#{repo_name}"
  puts "ENV['REPO_URL'] is not set. Falling back to #{repo_url}."
else
  repo_url = ENV['REPO_URL']
end

puts `git checkout master`
puts `git pull`
puts `git checkout develop`
puts `git pull`
puts `git checkout -b #{branch_name}`
puts `git merge master`

cmd = "git push -u origin #{branch_name}"
puts cmd
puts `#{cmd}`

title = URI.escape("[release] #{now} #{tz}")
compare_url = "#{repo_url}/compare/master...#{branch_name}?title=#{title}"

os = `uname -s`
case os
when /Linux/i
  ex = 'xdg-open'
  puts 'Linux!'
when /Darwin/i
  ex = 'open'
  puts 'Mac!'
else
  raise "Unexpected operating system: #{os}"
end

cmd = "#{ex} #{compare_url}"
puts cmd
puts `#{cmd}`
