version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - global-gem-cache
      - run:
          name: Install Slack Notifier
          command: (gem list -i slack-notifier) || (gem install slack-notifier)
      - run:
          name: Lint commits
          command: ./../circleci/commit-lint
      - save_cache:
          key: global-gem-cache
          paths:
            - vendor/gems
